name: UI Tests

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Тип тестов:'
        required: true
        default: 'all'
        options:
          - all
          - Authorization
          - Inventory

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        env:
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          if [ "${{ github.event.inputs.test-type }}" == "all" ]; then
            docker-compose up --exit-code-from regression || true
          elif [ "${{ github.event.inputs.test-type }}" == "Authorization" ]; then
            docker-compose up --exit-code-from regression || true
            /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results --allure-stories=Authorization"
          elif [ "${{ github.event.inputs.test-type }}" == "Inventory" ]; then
            docker-compose up --exit-code-from regression || true
            /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results --allure-stories=Inventory"
          fi

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history  # Создает директорию для истории Allure
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true